services:
  csharp-chessfiguresclassification_api:
    image: lukasmodry02/bp_chessgame_image_recognition:api
    container_name: csharp-chessfiguresclassification_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - chessnet

  csharp-chessnotationsgenerator:
    image: lukasmodry02/bp_chessgame_image_recognition:generator
    container_name: csharp-chessnotationsgenerator
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - csharp-chessfiguresclassification_api
    networks:
      - chessnet

networks:
  chessnet:
    driver: bridge
