services:
  csharp-chessfiguresclassification_api:
    build:
      context: .
      dockerfile: ChessFiguresClassification_Api/Dockerfile
    container_name: csharp-chessfiguresclassification_api
    restart: unless-stopped
    init: true
    ports:
      - "5000:5000"
    networks:
      - chessnet

  csharp-chessnotationsgenerator:
    build:
      context: .
      dockerfile: ChessNotationsGenerator/Dockerfile
    container_name: csharp-chessnotationsgenerator
    restart: unless-stopped
    init: true
    ports:
      - "8080:8080"
    networks:
      - chessnet
    depends_on:
      - csharp-chessfiguresclassification_api

networks:
  chessnet:
    driver: bridge
